services:
  project-manager:
    image: ghcr.io/donovandmc/project-manager
    container_name: project-manager
    volumes:
      - ./data/bot:/data
    restart: always
    hostname: project-manager.bots.containers.local
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://localhost:3621
    deploy:
        resources:
          limits:
            memory: 256M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.1.38

networks:
  default:
    name: project-manager
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.1.36/30
          gateway: 172.19.1.37
  websites:
    name: websites
    external: true
